# Generated by Django 4.1.7 on 2023-03-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_user_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Category',
            new_name='category',
        ),
    ]
